version: "3.4"
services:
  samba:
    image: willbeta/samba:arm64
    ports:
      - target: 137
        published: 137
        protocol: udp
        mode: host
      - target: 138
        published: 138
        protocol: udp
        mode: host
      - target: 139
        published: 139
        protocol: tcp
        mode: host
      - target: 445
        published: 445
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /mnt
        target: /shared/mnt
      - type: bind
        source: /media
        target: /shared/media
    hostname: rpi-samba
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.samba==true

